# Generated by Django 2.0.4 on 2018-05-29 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180527_0616'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='profile_image'),
        ),
    ]
