# Generated by Django 2.0.5 on 2018-08-03 22:10

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.FileField(default='media/profile_image/user_profile_pic_default.jpg', upload_to=accounts.models.user_directory_path),
        ),
    ]
