# Generated by Django 2.0.4 on 2018-05-30 00:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20180529_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='profile_image'),
            preserve_default=False,
        ),
    ]
