# Generated by Django 2.0.4 on 2018-05-29 23:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='profile_pic',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='profile_image'),
            preserve_default=False,
        ),
    ]
